### ISSUE TITLE
transform catart-mubu into a Max package

### ISSUE THREAD

**Issue by diemoschwarz** [ircam-ismm/catart-mubu#47]
this could augment adoption through the package manager, and make it easier to handle dependencies (on Mubu mainly, but also bach?). Any enthousiastic encouragements?

A guesstimate of the necessary steps:
- [x] #61
- [x] write the package description ReadMe 
- [x] write the package metadata json. [Cycling draft doc](https://github.com/Ircam-RnD/catart-mubu/files/9422966/The.package-info.json.file.pdf)
- [ ] #62
       *[If you plan to submit your Package for consideration](https://cycling74.com/support/submit-packages) for Cycling '74's Package Manager, you will need to have both a ReadMe and a License in your package.*
- [x] #60
- [x] #59
- [x] #67
- [ ] [upload to package manager](https://cycling74.com/support/submit-packages)

Cycling resources:
- [official documentation](https://docs.cycling74.com/max8/vignettes/packages) 
- [package authoring tutorial](https://cycling74.com/tutorials/package-authoring-an-introduction)

**Comment by einbond** [comment]
I'm up for it! Another step perhaps to add: make an overview patch to display in the Max Extras menu.

**Comment by christophertrapani** [comment]
I'm up for it too; it'd be great to polish things up. Admittedly a little busy, but let's try to make it happen!

**Comment by diemoschwarz** [comment]
Great to hear that, Chris!  I guess a brainstorming/suggestions/patch snippets about what should be in the "main" package intro/overview patch and the package description would be great.

**Comment by diemoschwarz** [comment]
Hi again, rethinking this, there are a few larger tasks I foolishly opened, like:
- #43 
- #49, with a parallel set of process modules 
- #53, which needs reworking of the poly voice modules
- and related #48, #56, #58 

Should we better finalize all these before releasing a package, or rather get the package out there with all the WIP patches removed, and then issue updates?
What are your thoughts on this, @einbond and @christophertrapani?

**Comment by christophertrapani** [comment]
Hi guys — I've just returned to the US and am happy to do some work on
this. Maybe a bit more free than usual these days...

Of the issues Diemo mentioned, maybe we could start with working on
segmentation issues? Some things (snapshots) are a bit beyond me but I am
happy to help...

C

**Comment by diemoschwarz** [comment]
Hiya, here in Normandy I've encountered temperatures under 25º for the first time since 5 months, I'm freezing!

I think we can advance in parallel, doing the package thing on github (so people can download it), while deciding on which issues are blocking the official release on the PM (to be added to https://github.com/Ircam-RnD/catart-mubu/milestone/11).  I fear trying to do all of them could delay this for a long time...
I split out the main patch to do as #59.

**Comment by diemoschwarz** [comment]
Hi @christophertrapani and @einbond, I made good progress sketching the camu package structure (#61) and content (#59).  It lives in branch [wip-max-package](https://github.com/Ircam-RnD/catart-mubu/tree/wip-max-package). Beware:  none of the bubble texts are updated yet, I'll need help with these once everything is there.

Any remarks on the structure (#59)? Any suggestions for a more self-standing overview patch design / typography / color scheme, without overdoing it (I copied the mubu one for now). Any favourite packages for an example?
Any opinions on the other points (logo #60 , license #62, readme)?

Best!

**Comment by christophertrapani** [comment]
Just downloaded and had a first look at the simple patch, which I think is
pretty much optimized already for straightforward presentation! A logo and
simple color scheme / typography standardization is a great idea, but I
can't say I have any real preferences. Same for license and readme...

**Comment by diemoschwarz** [comment]
All it took was asking...  to get more info on the package-info.json.
https://cycling74.com/forums/max-package-manager/replies/1#reply-62fdf81c31505b3b337d3f9b
[The package-info.json file.pdf](https://github.com/Ircam-RnD/catart-mubu/files/9422966/The.package-info.json.file.pdf)
