### ISSUE TITLE
stats for one marker?

### ISSUE THREAD

**Issue by einbond** [ircam-ismm/catart-mubu#55]
Question and/or possible feature request for mubu more generally: am I right that if a buffer has only one marker then no stats are returned, e.g. when sending the message "bufferindex $1, getmean" to mubu.track? I guess this is logical, but wouldn't it be technically correct to say the mean, min, and max of one number is just the number? This tripped me up because I was processing the mean descriptor values for a large number of buffers and when some of them returned no value the whole list was misaligned. Perhaps it would be safer if mubu returned some kind of response to "getmean" ?

**Comment by diemoschwarz** [comment]
That's clearly a mubu bug. Do you have access to copy this to the mubu bug tracker https://git.forum.ircam.fr/haddad/mubu/-/issues?

**Comment by einbond** [comment]
Yes, done, thanks!

**Comment by diemoschwarz** [comment]
should  be fixed in mubu 1.10.3, could you please verify, Aaron @einbond?
