### ISSUE TITLE
create minimal set of help patches

### ISSUE THREAD

**Issue by diemoschwarz** [ircam-ismm/catart-mubu#67]
see discussion on https://github.com/Ircam-RnD/catart-mubu/commit/fd107a7c59679ae186ddf3d5aaf2bf7c0d3c4424 and #59

**Comment by christophertrapani** [comment]
Ok, I will take:

camu.triggermode
camu.cont
camu.soundsettag
camu.filenamenotenumber
camu.record

A, how about you take:

camu.analysis
camu.select
camu.random
camu.random.filter
camu.autotag

D, the rest?

**Comment by christophertrapani** [comment]
Follow-up: Would you guys agree that once we have help files, it makes more
sense for the actual objects to be on the "abstractions" tab, rather than
the names in message boxes? I can reconfigure if you like...

**Comment by diemoschwarz** [comment]
OK for the partitioning.

I just added a first help as preview. Might needs to be even simpler to focus on the actual object.

>Would you guys agree that once we have help files, it makes more
sense for the actual objects to be on the "abstractions" tab, rather than
the names in message boxes?

I'd say no, a message box to click on directly is much more convenient.

**Comment by diemoschwarz** [comment]
## The Definite List of Help Patch Assignments

### Chris @christophertrapani 
- [ ] camu.cont
- [ ] camu.filenamenotenumber
- [ ] camu.record
- [ ] camu.soundsettag
- [ ] camu.triggermode

### Aaron @einbond 
- [ ] camu.analysis
- [ ] camu.autotag
- [ ] camu.random
- [ ] camu.random.filter
- [ ] camu.select
- [ ] camu.key.select.maxpat
- [ ] camu.key.soundset.maxpat
- [ ] camu.key.value.maxpat

### Diemo @diemoschwarz

- [ ] camu.control.blocks.maxpat
- [ ] camu.control.linnstrument.maxpat
- [ ] camu.control.mpe.maxpat
- [ ] camu.control.qwerty.maxpat
- [ ] camu.control.sensel.maxpat
- [ ] camu.imubu.control.maxpat
- [ ] camu.menu.maxpat
- [ ] camu.synth.poly~.maxpat
- [ ] camu.synth.poly~8ch.maxpat
- [ ] camu.synth.voice-8ch.maxpat
- [ ] camu.target.maxpat
- [ ] camu.voice.maxpat
- [ ] camu.voice.poly~.maxpat
- [ ] camu.voice.poly~8ch.maxpat
- [ ] camu.voice.poly~old.maxpat

### Later
- [ ] camu.alive-to-index.maxpat
- [ ] camu.debug.control.maxpat
- [ ] camu.debug.maxpat
- [ ] camu.filenamenotenumber.maxpat
- [ ] camu.id-to-index.maxpat
- [ ] camu.ircamdescriptor-menu.maxpat
- [ ] camu.pipo.descr-chop.maxpat
- [ ] camu.pipo.descr-gate.maxpat
- [ ] camu.pipo.descr-onseg.maxpat
- [ ] camu.pipo.ircamdescriptor-chop.maxpat
- [ ] camu.pipo.ircamdescriptor-gate.maxpat
- [ ] camu.pipo.ircamdescriptor-onseg.maxpat
- [ ] camu.process.descr-chop.maxpat
- [ ] camu.process.descr-gate.maxpat
- [ ] camu.process.descr-onseg-mono.maxpat
- [ ] camu.process.descr-onseg-xy.maxpat
- [ ] camu.process.descr-onseg.maxpat
- [ ] camu.process.ircamdescriptor-chop.maxpat
- [ ] camu.process.ircamdescriptor-gate.maxpat
- [ ] camu.process.ircamdescriptor-onseg.maxpat
- [ ] camu.process.mfcc-chop.maxpat
- [ ] camu.process.mfcc-gate.maxpat
- [ ] camu.process.mfcc-onseg.maxpat
- [ ] camu.process.off.maxpat
- [ ] camu.process2.descr-chop.maxpat
- [ ] camu.process2.descr-gate.maxpat
- [ ] camu.process2.descr-onseg.maxpat

### NOT
- [ ] camu.circle-player.maxpat
- [ ] camu.keymixer-horiz-data.maxpat
- [ ] camu.keymixer-horiz-level.maxpat
- [ ] camu.mpe-to-index.maxpat

**Comment by christophertrapani** [comment]
Let's move "camu.soundset.tag" to the NOT list then? Feel free to assign me a few more too...

**Comment by diemoschwarz** [comment]
@christophertrapani , I'm sure, Aaron wouldn't mind your stealing some of his list  ;-)

**Comment by diemoschwarz** [comment]
...and as I have spent so much time with camu.select, recently, I'm feeling intimate enough with it to steal it from @einbond

**Comment by einbond** [comment]
Nb. camu.autotag has been replaced by camu.key.value

**Comment by diemoschwarz** [comment]
Hi, we're almost there!  Aaron, are you on camu.analysis? If not we can hide it for the moment, it is not used in any patch, methinks.

**Comment by einbond** [comment]
Hi Diemo, sorry I haven’t managed it. Please hide it if you haven’t already! ;)

By the way I was going to raise this as an issue: should we put our names somewhere?

 Cheers, Aaron

**Comment by christophertrapani** [comment]
That would be fine by me.

**Comment by diemoschwarz** [comment]
Then we might be ready to merge the wip branch into main and tag everything as release 1.5?

**Comment by christophertrapani** [comment]
So, does this mean CaMu is also ready for theMax Package Manager? How do we
go about it getting it there?
