### ISSUE TITLE
getinfobuffer 0 / buffer 0 getinfo

### ISSUE THREAD

**Issue by christophertrapani** [ircam-ismm/catart-mubu#92]
Hi guys — I noticed a change in patch behavior with a recent mubu update. Are both "getinfobuffer 0" and "buffer 0 getinfo" supposed to work, or is "buffer 0 getinfo" now obsolete? It doesn't seem to be working with the latest MuBu, and a lot of our tutorials include it... Thanks — C

<img width="229" alt="Screenshot 2023-08-22 at 3 23 18 PM" src="https://github.com/ircam-ismm/catart-mubu/assets/35881355/fde81877-ddfb-4958-8110-91e258c050b0">

**Comment by diemoschwarz** [comment]
Hi Chris, please remind me, what was it supposed to be doing?

**Comment by christophertrapani** [comment]
In the key-mixer abstraction / tutorial, it was scanning all buffers for a
key and then a paired name.

**Comment by diemoschwarz** [comment]
good catch!  that was broken since 1 year.  Can you hold out until Riccardo can make a new release when he's back end of August?
