### ISSUE TITLE
consider if the package could work without the dependency on spat5, shell or any other library which is not available on the Package Manager

### ISSUE THREAD

**Issue by einbond** [ircam-ismm/catart-mubu#94]

**Comment by einbond** [comment]
- [ ] I can easily remove s2m from catoracle (@diemoschwarz it looks like you wrote s2m is available from the package manager, but I don't see it, and I cannot find a version for M1/M2)

- [ ] however, catoracle is dependent on shell and python (but not spat) and catart-mubu-spat is dependent on spat, so I think the best approach is to label them clearly in the patches tab, as we are doing.

**Comment by diemoschwarz** [comment]
that would be great!

**Comment by diemoschwarz** [comment]
could you also address this one on the go:

- [ ]  catoracle: It doesn't say what type of file to load in step 1. The m4a file I was using for every other patch does not work. The UI for this patch could be improved to make it easier to understand, and don't hide the toolbars.
