### ISSUE TITLE
catoracle: It doesn't say what type of file to load in step 1. The m4a file I was using for every other patch does not work. The UI for this patch could be improved to make it easier to understand, and don't hide the toolbars.

### ISSUE THREAD

**Issue by einbond** [ircam-ismm/catart-mubu#95]
- [x] It doesn't say what type of file to load in step 1. The m4a file I was using for every other patch does not work.
- [ ] The UI for this patch could be improved to make it easier to understand
- [x] and don't hide the toolbars.

**Comment by einbond** [comment]
The first point is because the Max "opendialog sound" object does not recognize m4a, so the Max team has themselves to blame! ;) Anyway, it looks like the other camu objects do not enforce file types, so I will revise this.

**Comment by einbond** [comment]
About the UI: open to suggestions!

**Comment by einbond** [comment]
I have completed this except for improving the UI.

**Comment by diemoschwarz** [comment]
I think we can leave this as it is. It is nicely documented and labeled as an advance patch.

**Comment by diemoschwarz** [comment]
as catoracle is no longer part of the main PM distribution (see #91), we can close this
