### ISSUE TITLE
revise camu.key.select / camu.key.soundset

### ISSUE THREAD

**Issue by diemoschwarz** [ircam-ismm/catart-mubu#96]
@christophertrapani, while hunting down the error messages from all patches for #91, in camu.key.soundset.maxhelp I came across a `buffer` message from camu.key.select, [p include-buffers] that now triggers a response from imubu that produces an error.
The comment is _make sure foremost buffer is in list_.
There is also `[vexpr $i1 + 1 @scalarmode 1]` _correct apparent bug in imubu for now_.
I wonder if both are still necessary or could be removed?
Otherwise the help patch will have to take care of that.

**Comment by einbond** [comment]
I think this is my doing...will take a look!

**Comment by christophertrapani** [comment]
Does this have to do with:
https://github.com/ircam-ismm/catart-mubu/issues/92 ?

Here's a newer version of "include-buffers" which we can substitute:

<pre><code>
----------begin_max5_patcher----------
3287.3oc6cs0bihbE9Y6eETZeIoJam9JWl2ljJaUopM6rUk71robgjZKyNHf
.HOdlsl+6ooaPBPBnQPC3My5sr8Pij936boO84zm1+9s2rZc3qrjUFuy3iF2
byue6M2HtT1EtI+eeyp8tutw2MQbaqBXeNb8us5N4PorWSEWNxvKXi+gsr6W
e3omXwI2i.Hbws8TXPZf6dl3VeermqewHQtoad1KX2iwrMoRbPPOPuy.id.b
mgic12gNO.L9O4uhfC6COj5yRE3AjeUush2aNztGRbJ+4l38UwmK+83z6fWP
wa.pLPXw4O44O572AOe1K7GGuvfrgf2kec2nnRW9lRujL952BEuQ12c7RdAx
KQOdoX1KdEudyiW0MlSGobt3Prjsd0jr5zaS3VVbvAOATjW7a2V.IgLJikSh
b2HewYhxhgOQvHAohMy9tMFl8CKJ5DEyUA14Gt4SrskX3aVEFwB7BhhYIrfT
2zbneb3srmbO3m9XYNGhd3hi+TN.u3fWTQ4lU6h81FFjAhJBhrKW7w8QCHUn
uPK+vHti.2nK7h4pKbVogAS3OjGRV6FmImV6yJosvU7CC8qNzwmEe1So4CG4
EDHYwRuvnlGL1a2ys7ZWGxGbeau2hQRd7PfbzG4pDoOl39hTZPOdit994Fxk
QNWcwMvauaJK0SJCPfiCxBb4OoOmrINz2uBQIG4kKLxVtN9F1m81l9r3Cpr1
.+18hJzhVcTLu0aGKIs50Rc2kT8JIoeQx5ktzg041vOlx1G4yeJpdCbqCujz
jmC+bR9MVnoUl.N4MrrMcYuhUtdMuiaB2umacbzhsrKxO7K+6+wG9Yi+lwO+
ge9uW3tb66L9puwg.u+6AlA+UG4xsuL74.0HMzHvy+NCtqffDivmdxfK0Lxc
uV9Sv2KfsI7Pf3igTZflslZv0KBhevh67kXJ7AaKbTPrJYM0nG35dgIqpAjy
7CetuXXw0+1s2V7K2oOIwe8c+Zv+5C+ySxheMXsavtLhOg4a.L9SYTuQXPFw
+m4BhmYA7QB1dT9HF+C+3OZvdU9Nzo3wYHhGqLgBEPxjJlhu6bUxF7LKa3SQ
k3ticQYyKdrOaH7NvEKtaR8dgI4TufsbeIIcPQl.XFIYhcx9ADSqG+vEXIXo
QjWN8KQ4SnrZUkWX4vLPlWAMhlHZj64nClBZQj15NYtkMPBBCgzBSAWME7Qk
PSqRGoFqMV2EgvMlxHDpkHzSY.ncPHn1HjLmIqtK+mMQNzl4F3TwM9Fcprvi
Yrm5JsRMYzRiTBBuZA4EJ2idHOnZuzuX.5fonljxZQPnk17.g.yrCn0G3wiF
zoYkXAFhkYfHEe+ZIiVskfVUwRLex0Td7fx.TqOg3R0VyBKrtLwBEGB9AjNM
1lc2O7k9wh8C+7pgDYDQ5s1T5ehz2Y8uzZR6os3BNjp7fS6z0EBKccYZIT8H
N5K1I3BNzoAFAJxAWIBT84+2FufYw70T0sRGDHU5j7EQezko8LSWs3D7q9FP
.++LRBiSGjmvrH0JsDdSjB7I5pbE11rJTmkKWms1dnAXXrbwZEx0WQpPy3qg
lqrHhVo7qY4n3IV8NOCWiC2KIc6YRCetc9pPBtduw6+oe5TlFqldKXi4nBOD
oCFYJxREpTX+3qJKUz4NlJUTn2EGdHZPpy4g6iEQtZAlEkYBY45t9vW8FF+B
Dwg4HbTS.SkeZuLaolna7afHQj0jXDTsy8SaQlEUa7BNRDtuiTlA+SNOGS44
ZZLT2MkEN2DKU9Ge8cAo2JwO2wiz1pS1wROQ6iAeCESzYZqsUufoKW83MOyc
5Mvf5nx7bgszre5Beyc3hFSVtAeHRhH+q0igyYpvsLEnfeBxf7SzUgPvf2FU
krd8.dvQsbSVTP.jo9JHvagLbjxomwICGX7LlgCzbmByzvc67YcwUhEiYBrK
LuGllWadLqVN7kXwWhh43u6b51eERAIaAPxHATQeDnf9XYtcAOazNWdLrCNe
ZR8T4xeI3ou7MnEb9JM9A386Or9vCeJXXdNKx0tERFdEvZ7UUULp+Mg9xMD6
G4yfZ6.fNl2w+MpIwBH9MfkMAC4n6bvM4p3BIfWlHXLJRoERt45z.4Cc9CH6
eVMy6u2EBRn2mmDHLRgfcGPE0gzEchKiCSMfCyOhMTvmXHUrU8s6YDX8iOcn
K5nZ83A4XfFFehcJymDfd4yEbxdy1md9iBWhnBacS3P4xNK7lCd4Zt6MP+l.
YRYH1J627pW+fCZQalGy1MN5k1h0+iw50FGtnIyfzmG3TPPpobewIqaFYdpa
lsyhllYa77SF5bS4sDRAQS0pdqs4Btp5h9+PTMc1eoXO0cHvKMYTBNUVdLfL
GMWUAyg1K2IhhhYQYcNSe1bc8euGXISHnbdJKzjmFAHftjKavZwW9iP8trDA
Df.PgSXcT2f50SuyvvffEbbXQFwta8BuOk++YWa3R.prfil5Lkt1VWi235n+
TSUWk7Zr4papAqq8xuTiV2PyV2bCW2cSW2TiWWo4qUnArq0D1l.gnSZHYRxm
bsVmQb4NwVgtwtwNxthfq8lxVwFytklyVsFztilztyF0tyl0tiF1t6l1tyF2
Vgl2VkF3tWMwcKMxcmMyc6Mzc6M0c6M1cqM2cSM38kax6FZzakZ1aEa36K2z
208yT2++Yi207.mEXd8cMX2SDzb34x.FMoMW4j1iPWwnzasENZe9gVhXuxLu
Um88sjTHKVS5rHE.uskBomEQ5fEBTmlSHP6ahnqXC3eVdWFf3.tHLJDoyFON
BDYmPAAfdIQFtUg8aaiB9D+ta9jQB+KudPyxDzPsGKE+hcsU8UHTmssVs70p
8yhscLzokanVDAd5HTZZbzSW35zmm3rZ6fNW+Cr6L9D6KFQtdU1zsWuzvQLe
KxRj2GYWqVO0Ysm9rynYzadG39ggeZrBqwIOEZx8j6Dps+VOpFv3v+HYQNxi
qDAUT..6R.zkKcy21VAhSuowUBHmb8xU.8ZLATJZR52Ct+3wphL3Fmd4HZbi
s+M9TC2a.GEIgrAM5qAwfcIY4787MTKJzoOcCVVeWHTykTdvmSnPfX+lWHjb
X835MJOECnoSHPeyKDFwEJTzloS85DHjEtTP7ooruDnvIBhV78gNmZ6IIC0Z
dapScEquudUVDuqAaYuNUg4nJkVjS9IkSoiOmNEpoxmRk0Sw4G.jpRpsjvEa
y1yd3XqEVspyYG6IcT5OAIjcesSmIgGh2TnijWI.CzY7xVVRpWvwx0+wi4q1
fygWkfdH3CpH9xp02r.Pfp.DLC.LyXWYD5LG.D0C.hlC.1C7YMC3ypO5fVyB
Bs5AByhV5B2bX7V4VzBtbgNrcjClVjuzccZszccZ1C.ZaNC.rOt1mC7QrW5L
HoOTnkybgPUsioyA.I8wNdNPHpGL3rL+Xeh.hXOS.T0kIPlCQLjtzoPHrmAR
.mZ.B5aPZSNB6qil1AXoAKuC4WksGl29nbub+naZZr25CoxEfeAjdcai3V1r
667CW65Waq.2zlP91ye1llNjJuyxFiy1KGQZZrrl79fxz4+KN5VOdRTAnxS.
nYoITMs9C9YscQWnCcl1iv0lY7k8Qs8XbHae7HofHOj0fZsseojE7eICj8mJ
e9wcL9zgOENPkYmRmWnJ4w35NK.ofkqWgrSRIie.NFm6pxR9NCSwQtpo3t9f
gX6Wegt.jynYgx3m0IkmUvjtND9JeC6ciht3sDyRb2G4yN9ITYzrGhcx1hr5
0CbihyaJqrYaqFH1Kr30gIrp4bbTiypdQBaVCBzb4AGE6PqF+6qT0CjqKVWq
KTSqIhbx96V1DvN1iC6bI+Vm9C.7YU46DgcoELUh1NunTmsZ3lxWTskw0pXq
2nfzGT.zEJv0y9SS09hpaTnBW3.0IJPJhBSKchBnpbgN0KrcTEEHMZiXaoHJ
DmaD5iLLU0HQqnPUiDjNAghXv1RipEV8ADUuwyq13rfLXKHCpEjYppAs4TyY
JiLzYUpP6jl8hkzrWtjlpFAHcNYtoYel.SqnPkYNfZkLnJahoyIvnpRFl15F
EJE2sVkHpF8uooNQgpgTP0JJTMhWartQw7qcBTjKHNZDEDU8Wf0odAQUaDcZ
nRTcAxDhtQAZtQAVY0BfNQgpNvIXciBklYGpyLmfoKA+EXU8ZYpcTfTJaA5T
jfrW.qSGY1m0GnMTnpySJVioK.oZTNXGchBUytHRmtvQpFqEUmVpHvRvDQ0n
KzIS.U2PUqn.tDLQfPph9Kr0pLAp5jp1lZEFK0jOoLxl9jOcbp840dRTNBrp
EzBpUX.m6JZIggJAlQAZGFJ4jSmgGB6SHQ5DDJ6t+xfH+hE6M3t1JL4now8C
7k1KvcrYequQekfS787cNP8Cf7LPT6.Gu1AM94Gv3MevhW+.EWPEMc.he62t
8+AaJaRM
-----------end_max5_patcher-----------
</code></pre>

**Comment by diemoschwarz** [comment]
thanks, Chris, that solves the bogus error message! Integrated in ff0d0f6
